version: '3.3'
services:
  db:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-spring
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/demo
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - db


# version: '3'
# services:
#   h2:
#     image: 'oscarfonts/h2:latest'
#     ports:
#       - '1521:1521'
#       - '8081:81'
#     environment:
#       H2_OPTIONS: -ifNotExists
#     volumes:
#     - ./h2/:/opt/h2-data
#     restart: 'always'
#   hello-spring:
#     build: .
#     ports:
#       - '8080:8080'
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:h2:tcp://localhost:1521/test
#       SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
#       SPRING_DATASOURCE_USERNAME: sa
#       SPRING_DATASOURCE_PASSWORD:
#       SPRING_JPA_SHOW_SQL: true
#       SPRING_JPA_HIBERNATE_DDL_AUTO: create
#       SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
#     depends_on:
#       - h2
